import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigrations1701673167804 implements MigrationInterface {
    name = 'InitialMigrations1701673167804'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "data_point" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "question_number" integer NOT NULL, "answer" character varying NOT NULL, "response_id" uuid, "interview_id" character varying(8), CONSTRAINT "UQ_c64580391d4e5234a9186bcb4b4" UNIQUE ("response_id", "question_number"), CONSTRAINT "PK_5ece4cf987960a4f58c092ff48f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "interview_flow" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "interview_id" character varying NOT NULL, "nodes" jsonb NOT NULL DEFAULT '[]', "edges" jsonb NOT NULL DEFAULT '[]', "functions" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "UQ_672bc8c155312e6764b601074fe" UNIQUE ("interview_id"), CONSTRAINT "REL_672bc8c155312e6764b601074f" UNIQUE ("interview_id"), CONSTRAINT "PK_39c5301c79de1de0205e89edac3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_672bc8c155312e6764b601074f" ON "interview_flow" ("interview_id") `);
        await queryRunner.query(`CREATE TABLE "phone_number" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "team_id" uuid NOT NULL, "phone_number" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'TOLL_FREE', "twilio_sid" character varying NOT NULL, "interview_id" character varying(8), "subscription_id" uuid, CONSTRAINT "REL_0cd238cb8951fb5b6b1e225740" UNIQUE ("interview_id"), CONSTRAINT "REL_0b493217cb31f066417a4624ce" UNIQUE ("subscription_id"), CONSTRAINT "PK_c16f58426537a660b3f2a26e983" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genius_source" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "genius_id" uuid, "name" character varying NOT NULL, "type" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'PROCESSING', "content" character varying, "file_url" character varying, "vectors" integer, "url" character varying, CONSTRAINT "PK_57094c2d4aa9cbb55fffa5e96a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genius" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "team_id" uuid, "name" character varying NOT NULL DEFAULT 'My Genius database', CONSTRAINT "PK_6e4208bcbae3cf26f7f8f86cb6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."interview_lang_enum" AS ENUM('en', 'es', 'it')`);
        await queryRunner.query(`CREATE TYPE "public"."interview_status_enum" AS ENUM('ACTIVE', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "interview" ("id" character varying(8) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "team_id" uuid NOT NULL, "genius_id" uuid, "type" character varying NOT NULL DEFAULT 'GENERAL', "title" character varying NOT NULL DEFAULT 'My thoughtly', "ai_name" character varying NOT NULL DEFAULT 'Tessa', "lang" "public"."interview_lang_enum" NOT NULL DEFAULT 'en', "error_id" character varying, "note_to_subject" text NOT NULL DEFAULT '', "notifications" boolean NOT NULL DEFAULT true, "status" "public"."interview_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_44c49a4feadefa5c6fa78bfb7d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "interview_deliverable" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "type" character varying NOT NULL, "video_url" character varying, "audio_url" character varying, "thumbnail_url" character varying, "image_urls" text array, "title" character varying, "content" character varying, "length_seconds" integer, "pov" character varying, "interview_response_id" uuid, CONSTRAINT "PK_84d05a58f30775bc7020cef795f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "interview_response" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "team_id" uuid NOT NULL, "type" character varying NOT NULL DEFAULT 'BROWSER_CALL', "status" character varying NOT NULL DEFAULT 'NOT_STARTED', "start_time" TIMESTAMP WITH TIME ZONE, "end_time" TIMESTAMP WITH TIME ZONE, "duration_ms" bigint NOT NULL DEFAULT '0', "conversation_history" jsonb NOT NULL DEFAULT '[]', "error_id" character varying, "ai_name" character varying NOT NULL, "twilio_sid" character varying, "phone_number" character varying, "interview_id" character varying(8), "contact_id" uuid, "job_id" uuid, CONSTRAINT "UQ_005ef464e151651bc23498f9de2" UNIQUE ("twilio_sid"), CONSTRAINT "PK_b882028ccf176842e4a11751fc5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_005ef464e151651bc23498f9de" ON "interview_response" ("twilio_sid") `);
        await queryRunner.query(`CREATE TABLE "contact" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "team_id" uuid, "status" character varying NOT NULL DEFAULT 'ACTIVE', "name" character varying DEFAULT '', "caller_type" character varying, "phone_number" character varying, "email" character varying, "tags" text array, CONSTRAINT "UQ_06b618690b4807b455028547ffb" UNIQUE ("team_id", "phone_number"), CONSTRAINT "PK_2cbbe00f59ab6b3bb5b8d19f989" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "team_id" uuid NOT NULL, "interview_id" character varying, "type" character varying NOT NULL DEFAULT 'CONTACTS', "rdd_config" jsonb, "status" character varying NOT NULL DEFAULT 'NOT_STARTED', "note" character varying, "logs" jsonb NOT NULL DEFAULT '[]', "payment_id" uuid, CONSTRAINT "REL_bb8b55c0f148cb8b2ec8453bd9" UNIQUE ("payment_id"), CONSTRAINT "PK_98ab1c14ff8d1cf80d18703b92f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "amount" numeric(10,2) NOT NULL, "payment_date" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL, "stripe_payment_id" character varying, "stripe_metadata" jsonb, "team_id" uuid, "invoice_id" uuid, CONSTRAINT "UQ_90c8716c0b894c76d1b72b813fe" UNIQUE ("stripe_payment_id"), CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90c8716c0b894c76d1b72b813f" ON "payment" ("stripe_payment_id") `);
        await queryRunner.query(`CREATE TABLE "invoice" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "amount" numeric(10,2) NOT NULL, "invoice_date" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL, "stripe_invoice_id" character varying, "stripe_metadata" jsonb, "team_id" uuid, "subscription_id" uuid, CONSTRAINT "UQ_6af71bd6c8f2397aa3a1e4bfe6a" UNIQUE ("stripe_invoice_id"), CONSTRAINT "PK_15d25c200d9bcd8a33f698daf18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6af71bd6c8f2397aa3a1e4bfe6" ON "invoice" ("stripe_invoice_id") `);
        await queryRunner.query(`CREATE TABLE "subscription" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "team_id" uuid NOT NULL, "plan" character varying NOT NULL DEFAULT 'BASIC', "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL, "stripe_subscription_id" character varying, "stripe_metadata" jsonb, CONSTRAINT "UQ_4919f4488c35799176dfd3c143d" UNIQUE ("stripe_subscription_id"), CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4919f4488c35799176dfd3c143" ON "subscription" ("stripe_subscription_id") `);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "team_status" character varying NOT NULL DEFAULT 'ACTIVE', "email" character varying NOT NULL, "phone_number" character varying, "first_name" character varying, "last_name" character varying, "avatar" character varying, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`CREATE TABLE "team" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "version" integer NOT NULL DEFAULT '0', "name" character varying, "name_pronunciation" character varying, "stripe_customer_id" character varying, "stripe_metadata" jsonb, CONSTRAINT "UQ_82ab6b327ae2b82eb48623ac433" UNIQUE ("stripe_customer_id"), CONSTRAINT "PK_f57d8293406df4af348402e4b74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82ab6b327ae2b82eb48623ac43" ON "team" ("stripe_customer_id") `);
        await queryRunner.query(`CREATE TABLE "job_contacts" ("contact_id" uuid NOT NULL, "job_id" uuid NOT NULL, CONSTRAINT "PK_4ec8eaa865b8796c3a3a7172136" PRIMARY KEY ("contact_id", "job_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e94272ae63eb038fc7f3493274" ON "job_contacts" ("contact_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad16631615a3349d62a10fbc15" ON "job_contacts" ("job_id") `);
        await queryRunner.query(`CREATE TABLE "user_teams" ("user_id" uuid NOT NULL, "team_id" uuid NOT NULL, CONSTRAINT "PK_73a4ff91e5f6ff3eae7356555ab" PRIMARY KEY ("user_id", "team_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee838ec2b13ac600a162c20ce3" ON "user_teams" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_006715ef1e1b40852f379efe56" ON "user_teams" ("team_id") `);
        await queryRunner.query(`ALTER TABLE "data_point" ADD CONSTRAINT "FK_8f3ed3370b55ef91be3dfeb3a44" FOREIGN KEY ("response_id") REFERENCES "interview_response"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_point" ADD CONSTRAINT "FK_33b16b71c6a7db11b4437e36596" FOREIGN KEY ("interview_id") REFERENCES "interview"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview_flow" ADD CONSTRAINT "FK_672bc8c155312e6764b601074fe" FOREIGN KEY ("interview_id") REFERENCES "interview"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "phone_number" ADD CONSTRAINT "FK_4813a1d30a1a94651fc909e8552" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "phone_number" ADD CONSTRAINT "FK_0cd238cb8951fb5b6b1e2257403" FOREIGN KEY ("interview_id") REFERENCES "interview"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "phone_number" ADD CONSTRAINT "FK_0b493217cb31f066417a4624ce8" FOREIGN KEY ("subscription_id") REFERENCES "subscription"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genius_source" ADD CONSTRAINT "FK_5ccf9bff2552c9261dda6b84907" FOREIGN KEY ("genius_id") REFERENCES "genius"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genius" ADD CONSTRAINT "FK_2d97b161bc9fbe06d94fe4113ff" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview" ADD CONSTRAINT "FK_8fff051a6add448da50d15f4e76" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview" ADD CONSTRAINT "FK_ce963ee0f060d667568cc17f58a" FOREIGN KEY ("genius_id") REFERENCES "genius"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview_deliverable" ADD CONSTRAINT "FK_447ef02ea36f7f0c19970ccf0f0" FOREIGN KEY ("interview_response_id") REFERENCES "interview_response"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview_response" ADD CONSTRAINT "FK_d13f9c17e6985c56e52e72dd11f" FOREIGN KEY ("interview_id") REFERENCES "interview"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview_response" ADD CONSTRAINT "FK_cf024f312a6a9044ec7217552fc" FOREIGN KEY ("contact_id") REFERENCES "contact"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview_response" ADD CONSTRAINT "FK_8abc67c63ba74e7e78552572e46" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview_response" ADD CONSTRAINT "FK_e445f24a7f31d446db8f503a8fb" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact" ADD CONSTRAINT "FK_659eb54c885c74a1e1bba956d83" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_ed903d246ba88c5df6cd1a175d0" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_f6609b708c36a91d3a211f25acc" FOREIGN KEY ("interview_id") REFERENCES "interview"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_bb8b55c0f148cb8b2ec8453bd9c" FOREIGN KEY ("payment_id") REFERENCES "payment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_c167b55fc6ce66304be1f00c7e6" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_20cc84d8a2274ae86f551360c11" FOREIGN KEY ("invoice_id") REFERENCES "invoice"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_8c8b0d3da1fa7ad8cf40aaade14" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_5d9508325a862b5b3c7c819de3e" FOREIGN KEY ("subscription_id") REFERENCES "subscription"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_04f564b652750165a1ceee013c5" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_contacts" ADD CONSTRAINT "FK_e94272ae63eb038fc7f34932746" FOREIGN KEY ("contact_id") REFERENCES "contact"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "job_contacts" ADD CONSTRAINT "FK_ad16631615a3349d62a10fbc152" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_teams" ADD CONSTRAINT "FK_ee838ec2b13ac600a162c20ce33" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_teams" ADD CONSTRAINT "FK_006715ef1e1b40852f379efe567" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_bb8b55c0f148cb8b2ec8453bd9c"`);
        await queryRunner.query(`CREATE TABLE "contact_tag" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, CONSTRAINT "PK_e46544545a47cff21d83da44cf1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4f430fb165d3f0dfdfe5121c7c" ON "contact_tag" ("name") `);
        await queryRunner.query(`CREATE TABLE "contact_tags" ("contact_id" uuid NOT NULL, "tag_id" uuid NOT NULL, CONSTRAINT "PK_b3c7d2660d12e8a6b26fd3ea967" PRIMARY KEY ("contact_id", "tag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_407719c80bcd1eb90c6d49a853" ON "contact_tags" ("contact_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca1290b9eb235a665c256a844a" ON "contact_tags" ("tag_id") `);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "REL_bb8b55c0f148cb8b2ec8453bd9"`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "payment_id"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "team_status"`);
        await queryRunner.query(`ALTER TABLE "contact" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "contact_tags" ADD CONSTRAINT "FK_407719c80bcd1eb90c6d49a8538" FOREIGN KEY ("contact_id") REFERENCES "contact"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "contact_tags" ADD CONSTRAINT "FK_ca1290b9eb235a665c256a844ad" FOREIGN KEY ("tag_id") REFERENCES "contact_tag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "contact_tags" DROP CONSTRAINT "FK_ca1290b9eb235a665c256a844ad"`);
        await queryRunner.query(`ALTER TABLE "contact_tags" DROP CONSTRAINT "FK_407719c80bcd1eb90c6d49a8538"`);
        await queryRunner.query(`ALTER TABLE "contact" ADD "tags" text array`);
        await queryRunner.query(`ALTER TABLE "user" ADD "team_status" character varying NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "job" ADD "payment_id" uuid`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "REL_bb8b55c0f148cb8b2ec8453bd9" UNIQUE ("payment_id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca1290b9eb235a665c256a844a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_407719c80bcd1eb90c6d49a853"`);
        await queryRunner.query(`DROP TABLE "contact_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f430fb165d3f0dfdfe5121c7c"`);
        await queryRunner.query(`DROP TABLE "contact_tag"`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_bb8b55c0f148cb8b2ec8453bd9c" FOREIGN KEY ("payment_id") REFERENCES "payment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_teams" DROP CONSTRAINT "FK_006715ef1e1b40852f379efe567"`);
        await queryRunner.query(`ALTER TABLE "user_teams" DROP CONSTRAINT "FK_ee838ec2b13ac600a162c20ce33"`);
        await queryRunner.query(`ALTER TABLE "job_contacts" DROP CONSTRAINT "FK_ad16631615a3349d62a10fbc152"`);
        await queryRunner.query(`ALTER TABLE "job_contacts" DROP CONSTRAINT "FK_e94272ae63eb038fc7f34932746"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_04f564b652750165a1ceee013c5"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "FK_5d9508325a862b5b3c7c819de3e"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "FK_8c8b0d3da1fa7ad8cf40aaade14"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_20cc84d8a2274ae86f551360c11"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_c167b55fc6ce66304be1f00c7e6"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_bb8b55c0f148cb8b2ec8453bd9c"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_f6609b708c36a91d3a211f25acc"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_ed903d246ba88c5df6cd1a175d0"`);
        await queryRunner.query(`ALTER TABLE "contact" DROP CONSTRAINT "FK_659eb54c885c74a1e1bba956d83"`);
        await queryRunner.query(`ALTER TABLE "interview_response" DROP CONSTRAINT "FK_e445f24a7f31d446db8f503a8fb"`);
        await queryRunner.query(`ALTER TABLE "interview_response" DROP CONSTRAINT "FK_8abc67c63ba74e7e78552572e46"`);
        await queryRunner.query(`ALTER TABLE "interview_response" DROP CONSTRAINT "FK_cf024f312a6a9044ec7217552fc"`);
        await queryRunner.query(`ALTER TABLE "interview_response" DROP CONSTRAINT "FK_d13f9c17e6985c56e52e72dd11f"`);
        await queryRunner.query(`ALTER TABLE "interview_deliverable" DROP CONSTRAINT "FK_447ef02ea36f7f0c19970ccf0f0"`);
        await queryRunner.query(`ALTER TABLE "interview" DROP CONSTRAINT "FK_ce963ee0f060d667568cc17f58a"`);
        await queryRunner.query(`ALTER TABLE "interview" DROP CONSTRAINT "FK_8fff051a6add448da50d15f4e76"`);
        await queryRunner.query(`ALTER TABLE "genius" DROP CONSTRAINT "FK_2d97b161bc9fbe06d94fe4113ff"`);
        await queryRunner.query(`ALTER TABLE "genius_source" DROP CONSTRAINT "FK_5ccf9bff2552c9261dda6b84907"`);
        await queryRunner.query(`ALTER TABLE "phone_number" DROP CONSTRAINT "FK_0b493217cb31f066417a4624ce8"`);
        await queryRunner.query(`ALTER TABLE "phone_number" DROP CONSTRAINT "FK_0cd238cb8951fb5b6b1e2257403"`);
        await queryRunner.query(`ALTER TABLE "phone_number" DROP CONSTRAINT "FK_4813a1d30a1a94651fc909e8552"`);
        await queryRunner.query(`ALTER TABLE "interview_flow" DROP CONSTRAINT "FK_672bc8c155312e6764b601074fe"`);
        await queryRunner.query(`ALTER TABLE "data_point" DROP CONSTRAINT "FK_33b16b71c6a7db11b4437e36596"`);
        await queryRunner.query(`ALTER TABLE "data_point" DROP CONSTRAINT "FK_8f3ed3370b55ef91be3dfeb3a44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_006715ef1e1b40852f379efe56"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee838ec2b13ac600a162c20ce3"`);
        await queryRunner.query(`DROP TABLE "user_teams"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad16631615a3349d62a10fbc15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e94272ae63eb038fc7f3493274"`);
        await queryRunner.query(`DROP TABLE "job_contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82ab6b327ae2b82eb48623ac43"`);
        await queryRunner.query(`DROP TABLE "team"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4919f4488c35799176dfd3c143"`);
        await queryRunner.query(`DROP TABLE "subscription"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6af71bd6c8f2397aa3a1e4bfe6"`);
        await queryRunner.query(`DROP TABLE "invoice"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90c8716c0b894c76d1b72b813f"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TABLE "job"`);
        await queryRunner.query(`DROP TABLE "contact"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_005ef464e151651bc23498f9de"`);
        await queryRunner.query(`DROP TABLE "interview_response"`);
        await queryRunner.query(`DROP TABLE "interview_deliverable"`);
        await queryRunner.query(`DROP TABLE "interview"`);
        await queryRunner.query(`DROP TYPE "public"."interview_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."interview_lang_enum"`);
        await queryRunner.query(`DROP TABLE "genius"`);
        await queryRunner.query(`DROP TABLE "genius_source"`);
        await queryRunner.query(`DROP TABLE "phone_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_672bc8c155312e6764b601074f"`);
        await queryRunner.query(`DROP TABLE "interview_flow"`);
        await queryRunner.query(`DROP TABLE "data_point"`);
    }

}
