name: Delete Preview Environment

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      INSTANCE_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_INSTANCE_CONNECTION_NAME }}

    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Delete Cloud Run services
        run: |
          gcloud run services delete api-pr-${{ github.event.number }} --platform=managed --region=us-central1 --quiet --project=${{ secrets.GCP_PROJECT_ID }}
          gcloud run services delete dashboard-pr-${{ github.event.number }} --platform=managed --region=us-central1 --quiet --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Delete Cloud SQL database
        run: |
          DB_NAME="pr-${{ github.event.number }}"
          INSTANCE_NAME=$(echo $INSTANCE_CONNECTION_NAME | cut -d':' -f3)
          gcloud sql databases delete $DB_NAME --instance=$INSTANCE_NAME --project=${{ secrets.GCP_PROJECT_ID }} --quiet

      - name: Patch Cloud SQL instance activation policy back to default
        run: |
          gcloud sql instances patch $INSTANCE_CONNECTION_NAME --activation-policy ALWAYS --project=${{ secrets.GCP_PROJECT_ID }}



# name: Delete Preview Environment

# on:
#   pull_request:
#     types: [closed]

# jobs:
#   delete-environment:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Authenticate to GCP
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}

#       - name: Delete Cloud Run services
#         run: |
#           gcloud run services delete api-pr-${{ github.event.number }} --platform=managed --region=us-central1 --quiet --project=${{ secrets.GCP_PROJECT_ID }}
#           gcloud run services delete dashboard-pr-${{ github.event.number }} --platform=managed --region=us-central1 --quiet --project=${{ secrets.GCP_PROJECT_ID }}

#       - name: Delete the database
#         run: |
#           DB_NAME="pr-${{ github.event.number }}"
#           INSTANCE_CONNECTION_NAME="${{ secrets.CLOUD_SQL_INSTANCE_CONNECTION_NAME }}"
#           INSTANCE_NAME=$(echo $INSTANCE_CONNECTION_NAME | cut -d':' -f3)
#           gcloud sql databases delete $DB_NAME --instance=$INSTANCE_NAME --quiet --project=${{ secrets.GCP_PROJECT_ID }}


# name: Delete Preview Environment

# on:
#   pull_request:
#     types: [closed]

# jobs:
#   delete-environment:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Authenticate to GCP
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}

#       - name: Delete Cloud Run services
#         run: |
#           gcloud run services delete api-pr-${{ github.event.number }} --platform=managed --region=us-central1 --quiet
#           gcloud run services delete dashboard-pr-${{ github.event.number }} --platform=managed --region=us-central1 --quiet

#       - name: Delete the database
#         run: |
#           DB_NAME="pr-${{ github.event.number }}"
#           gcloud sql databases delete $DB_NAME --instance=${{ secrets.CLOUD_SQL_INSTANCE_CONNECTION_NAME }} --quiet

# name: Delete Preview Environment

# on:
#   pull_request:
#     types: [closed]

# jobs:
#   delete-environment:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}

#       - name: Authenticate to GCP
#         run: |
#           echo ${{ secrets.GCP_SA_KEY }} | gcloud auth activate-service-account --key-file=-

#       - name: Delete Cloud Run services
#         run: |
#           gcloud run services delete api-pr-${{ github.event.number }} --platform=managed --region=us-east4 --quiet
#           gcloud run services delete dashboard-pr-${{ github.event.number }} --platform=managed --region=us-east4 --quiet

#       - name: Delete the database
#         run: |
#           DB_NAME="pr-${{ github.event.number }}"
#           gcloud sql databases delete $DB_NAME --instance=${{ secrets.CLOUD_SQL_INSTANCE_CONNECTION_NAME }} --quiet




# name: PR Cleanup

# on:
#   pull_request:
#     types: [closed]

# jobs:
#   cleanup:
#     runs-on: ubuntu-latest
#  git config --global user.email "nithinthadem@zemosolabs.com"
#   git config --global user.name "NithinThadem"
#     steps:
#       - name: Set up Google Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true

#       - name: Delete PR database
#         run: |
#           DB_NAME="pr-${{ github.event.number }}"
#           gcloud sql databases delete $DB_NAME --instance=$DB_INSTANCE --quiet
#         env:
#           DB_INSTANCE: ${{ secrets.DB_INSTANCE }}

#       - name: Delete API service
#         run: |
#           gcloud run services delete api-pr-${{ github.event.number }} --platform managed --region ${{ secrets.GCP_REGION }} --quiet
     
#       - name: Delete Dashboard service
#         run: |
#           gcloud run services delete dashboard-pr-${{ github.event.number }} --platform managed --region ${{ secrets.GCP_REGION }} --quiet


